"""
Catálogo canónico completo de juegos de la saga principal de Pokémon para el Selector de Juegos (Game Hub).
Define el orden cronológico estricto (3 por fila continua), mascotas, plataformas y estilos temáticos.
"""

MAIN_SERIES_GAMES = [
    # --- Generación 1 (Game Boy) ---
    {
        "slug": "red",
        "name": "Pokémon Rojo",
        "generation": 1,
        "platform": "Game Boy",
        "mascot_name": "Charizard",
        "mascot_num": 6,
        "header_bg": "bg-red-600",
        "header_text": "text-white",
        "badge_bg": "bg-red-500 text-white",
        "border_color": "border-red-600",
        "progress_color": "bg-red-600",
    },
    {
        "slug": "blue",
        "name": "Pokémon Azul",
        "generation": 1,
        "platform": "Game Boy",
        "mascot_name": "Blastoise",
        "mascot_num": 9,
        "header_bg": "bg-blue-600",
        "header_text": "text-white",
        "badge_bg": "bg-blue-500 text-white",
        "border_color": "border-blue-600",
        "progress_color": "bg-blue-600",
    },
    {
        "slug": "yellow",
        "name": "Pokémon Amarillo",
        "generation": 1,
        "platform": "Game Boy",
        "mascot_name": "Pikachu",
        "mascot_num": 25,
        "header_bg": "bg-amber-400",
        "header_text": "text-slate-950 font-black",
        "badge_bg": "bg-amber-400 text-slate-950",
        "border_color": "border-amber-400",
        "progress_color": "bg-amber-400",
    },

    # --- Generación 2 (Game Boy Color) ---
    {
        "slug": "gold",
        "name": "Pokémon Oro",
        "generation": 2,
        "platform": "Game Boy Color",
        "mascot_name": "Ho-Oh",
        "mascot_num": 250,
        "header_bg": "bg-[#c59b27]",
        "header_text": "text-slate-950 font-black",
        "badge_bg": "bg-[#c59b27] text-slate-950",
        "border_color": "border-[#c59b27]",
        "progress_color": "bg-[#c59b27]",
    },
    {
        "slug": "silver",
        "name": "Pokémon Plata",
        "generation": 2,
        "platform": "Game Boy Color",
        "mascot_name": "Lugia",
        "mascot_num": 249,
        "header_bg": "bg-slate-500",
        "header_text": "text-white font-black",
        "badge_bg": "bg-slate-400 text-white",
        "border_color": "border-slate-500",
        "progress_color": "bg-slate-500",
    },
    {
        "slug": "crystal",
        "name": "Pokémon Cristal",
        "generation": 2,
        "platform": "Game Boy Color",
        "mascot_name": "Suicune",
        "mascot_num": 245,
        "header_bg": "bg-sky-500",
        "header_text": "text-slate-950 font-black",
        "badge_bg": "bg-sky-400 text-slate-950",
        "border_color": "border-sky-500",
        "progress_color": "bg-sky-500",
    },

    # --- Generación 3 (Game Boy Advance) ---
    {
        "slug": "ruby",
        "name": "Pokémon Rubí",
        "generation": 3,
        "platform": "Game Boy Advance",
        "mascot_name": "Groudon",
        "mascot_num": 383,
        "header_bg": "bg-rose-900",
        "header_text": "text-rose-100 font-black",
        "badge_bg": "bg-rose-800 text-rose-100",
        "border_color": "border-rose-900",
        "progress_color": "bg-rose-800",
    },
    {
        "slug": "sapphire",
        "name": "Pokémon Zafiro",
        "generation": 3,
        "platform": "Game Boy Advance",
        "mascot_name": "Kyogre",
        "mascot_num": 382,
        "header_bg": "bg-[#0f3870]",
        "header_text": "text-sky-100 font-black",
        "badge_bg": "bg-[#0f3870] text-sky-100",
        "border_color": "border-[#0f3870]",
        "progress_color": "bg-[#0f3870]",
    },
    {
        "slug": "emerald",
        "name": "Pokémon Esmeralda",
        "generation": 3,
        "platform": "Game Boy Advance",
        "mascot_name": "Rayquaza",
        "mascot_num": 384,
        "header_bg": "bg-[#059669]",
        "header_text": "text-emerald-100 font-black",
        "badge_bg": "bg-[#059669] text-emerald-100",
        "border_color": "border-[#059669]",
        "progress_color": "bg-[#059669]",
    },
    {
        "slug": "firered",
        "name": "Pokémon Rojo Fuego",
        "generation": 3,
        "platform": "Game Boy Advance",
        "mascot_name": "Charizard",
        "mascot_num": 6,
        "header_bg": "bg-[#ea580c]",
        "header_text": "text-white font-black",
        "badge_bg": "bg-orange-600 text-white",
        "border_color": "border-orange-600",
        "progress_color": "bg-[#ea580c]",
    },
    {
        "slug": "leafgreen",
        "name": "Pokémon Verde Hoja",
        "generation": 3,
        "platform": "Game Boy Advance",
        "mascot_name": "Venusaur",
        "mascot_num": 3,
        "header_bg": "bg-[#16a34a]",
        "header_text": "text-emerald-100 font-black",
        "badge_bg": "bg-emerald-600 text-white",
        "border_color": "border-emerald-600",
        "progress_color": "bg-[#16a34a]",
    },

    # --- Generación 4 (Nintendo DS) ---
    {
        "slug": "diamond",
        "name": "Pokémon Diamante",
        "generation": 4,
        "platform": "Nintendo DS",
        "mascot_name": "Dialga",
        "mascot_num": 483,
        "header_bg": "bg-[#1e40af]",
        "header_text": "text-blue-100 font-black",
        "badge_bg": "bg-blue-700 text-white",
        "border_color": "border-blue-700",
        "progress_color": "bg-[#1e40af]",
    },
    {
        "slug": "pearl",
        "name": "Pokémon Perla",
        "generation": 4,
        "platform": "Nintendo DS",
        "mascot_name": "Palkia",
        "mascot_num": 484,
        "header_bg": "bg-[#be185d]",
        "header_text": "text-pink-100 font-black",
        "badge_bg": "bg-pink-700 text-white",
        "border_color": "border-pink-700",
        "progress_color": "bg-[#be185d]",
    },
    {
        "slug": "platinum",
        "name": "Pokémon Platino",
        "generation": 4,
        "platform": "Nintendo DS",
        "mascot_name": "Giratina",
        "mascot_num": 487,
        "header_bg": "bg-[#475569]",
        "header_text": "text-slate-100 font-black",
        "badge_bg": "bg-slate-700 text-white",
        "border_color": "border-slate-700",
        "progress_color": "bg-[#475569]",
    },
    {
        "slug": "heartgold",
        "name": "Pokémon Oro HeartGold",
        "generation": 4,
        "platform": "Nintendo DS",
        "mascot_name": "Ho-Oh",
        "mascot_num": 250,
        "header_bg": "bg-[#b45309]",
        "header_text": "text-amber-100 font-black",
        "badge_bg": "bg-amber-700 text-white",
        "border_color": "border-amber-700",
        "progress_color": "bg-[#b45309]",
    },
    {
        "slug": "soulsilver",
        "name": "Pokémon Plata SoulSilver",
        "generation": 4,
        "platform": "Nintendo DS",
        "mascot_name": "Lugia",
        "mascot_num": 249,
        "header_bg": "bg-[#64748b]",
        "header_text": "text-slate-100 font-black",
        "badge_bg": "bg-slate-600 text-white",
        "border_color": "border-slate-600",
        "progress_color": "bg-[#64748b]",
    },

    # --- Generación 5 (Nintendo DS) ---
    {
        "slug": "black",
        "name": "Pokémon Negro",
        "generation": 5,
        "platform": "Nintendo DS",
        "mascot_name": "Reshiram",
        "mascot_num": 643,
        "header_bg": "bg-slate-900",
        "header_text": "text-slate-100 font-black",
        "badge_bg": "bg-slate-800 text-white",
        "border_color": "border-slate-900",
        "progress_color": "bg-slate-900",
    },
    {
        "slug": "white",
        "name": "Pokémon Blanco",
        "generation": 5,
        "platform": "Nintendo DS",
        "mascot_name": "Zekrom",
        "mascot_num": 644,
        "header_bg": "bg-slate-200",
        "header_text": "text-slate-900 font-black",
        "badge_bg": "bg-slate-300 text-slate-900",
        "border_color": "border-slate-400",
        "progress_color": "bg-slate-400",
    },
    {
        "slug": "black-2",
        "name": "Pokémon Negro 2",
        "generation": 5,
        "platform": "Nintendo DS",
        "mascot_name": "Kyurem Negro",
        "mascot_num": 646,
        "header_bg": "bg-[#0f172a]",
        "header_text": "text-sky-200 font-black",
        "badge_bg": "bg-slate-950 text-sky-300",
        "border_color": "border-slate-950",
        "progress_color": "bg-sky-600",
    },
    {
        "slug": "white-2",
        "name": "Pokémon Blanco 2",
        "generation": 5,
        "platform": "Nintendo DS",
        "mascot_name": "Kyurem Blanco",
        "mascot_num": 646,
        "header_bg": "bg-[#cbd5e1]",
        "header_text": "text-rose-950 font-black",
        "badge_bg": "bg-slate-300 text-rose-800",
        "border_color": "border-rose-400",
        "progress_color": "bg-rose-500",
    },

    # --- Generación 6 (Nintendo 3DS) ---
    {
        "slug": "x",
        "name": "Pokémon X",
        "generation": 6,
        "platform": "Nintendo 3DS",
        "mascot_name": "Xerneas",
        "mascot_num": 716,
        "header_bg": "bg-blue-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-blue-500 text-white",
        "border_color": "border-blue-600",
        "progress_color": "bg-blue-600",
    },
    {
        "slug": "y",
        "name": "Pokémon Y",
        "generation": 6,
        "platform": "Nintendo 3DS",
        "mascot_name": "Yveltal",
        "mascot_num": 717,
        "header_bg": "bg-red-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-red-500 text-white",
        "border_color": "border-red-600",
        "progress_color": "bg-red-600",
    },
    {
        "slug": "omega-ruby",
        "name": "Pokémon Rubí Omega",
        "generation": 6,
        "platform": "Nintendo 3DS",
        "mascot_name": "Groudon Primigenio",
        "mascot_num": 383,
        "header_bg": "bg-rose-800",
        "header_text": "text-rose-100 font-black",
        "badge_bg": "bg-rose-700 text-white",
        "border_color": "border-rose-800",
        "progress_color": "bg-rose-800",
    },
    {
        "slug": "alpha-sapphire",
        "name": "Pokémon Zafiro Alfa",
        "generation": 6,
        "platform": "Nintendo 3DS",
        "mascot_name": "Kyogre Primigenio",
        "mascot_num": 382,
        "header_bg": "bg-indigo-900",
        "header_text": "text-indigo-100 font-black",
        "badge_bg": "bg-indigo-800 text-white",
        "border_color": "border-indigo-900",
        "progress_color": "bg-indigo-800",
    },

    # --- Generación 7 (Nintendo 3DS & Nintendo Switch) ---
    {
        "slug": "sun",
        "name": "Pokémon Sol",
        "generation": 7,
        "platform": "Nintendo 3DS",
        "mascot_name": "Solgaleo",
        "mascot_num": 791,
        "header_bg": "bg-orange-500",
        "header_text": "text-white font-black",
        "badge_bg": "bg-orange-600 text-white",
        "border_color": "border-orange-500",
        "progress_color": "bg-orange-500",
    },
    {
        "slug": "moon",
        "name": "Pokémon Luna",
        "generation": 7,
        "platform": "Nintendo 3DS",
        "mascot_name": "Lunala",
        "mascot_num": 792,
        "header_bg": "bg-indigo-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-indigo-500 text-white",
        "border_color": "border-indigo-600",
        "progress_color": "bg-indigo-600",
    },
    {
        "slug": "ultra-sun",
        "name": "Pokémon Ultra Sol",
        "generation": 7,
        "platform": "Nintendo 3DS",
        "mascot_name": "Necrozma Melena Crepuscular",
        "mascot_num": 800,
        "header_bg": "bg-amber-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-amber-700 text-white",
        "border_color": "border-amber-600",
        "progress_color": "bg-amber-600",
    },
    {
        "slug": "ultra-moon",
        "name": "Pokémon Ultra Luna",
        "generation": 7,
        "platform": "Nintendo 3DS",
        "mascot_name": "Necrozma Alas del Alba",
        "mascot_num": 800,
        "header_bg": "bg-blue-700",
        "header_text": "text-white font-black",
        "badge_bg": "bg-blue-800 text-white",
        "border_color": "border-blue-700",
        "progress_color": "bg-blue-700",
    },
    {
        "slug": "lets-go-pikachu",
        "name": "Pokémon: Let's Go, Pikachu!",
        "generation": 7,
        "platform": "Nintendo Switch",
        "mascot_name": "Pikachu",
        "mascot_num": 25,
        "header_bg": "bg-yellow-400",
        "header_text": "text-slate-950 font-black",
        "badge_bg": "bg-yellow-500 text-slate-950",
        "border_color": "border-yellow-400",
        "progress_color": "bg-yellow-400",
    },
    {
        "slug": "lets-go-eevee",
        "name": "Pokémon: Let's Go, Eevee!",
        "generation": 7,
        "platform": "Nintendo Switch",
        "mascot_name": "Eevee",
        "mascot_num": 133,
        "header_bg": "bg-[#a16207]",
        "header_text": "text-amber-100 font-black",
        "badge_bg": "bg-[#854d0e] text-amber-100",
        "border_color": "border-[#a16207]",
        "progress_color": "bg-[#a16207]",
    },

    # --- Generación 8 (Nintendo Switch) ---
    {
        "slug": "sword",
        "name": "Pokémon Espada",
        "generation": 8,
        "platform": "Nintendo Switch",
        "mascot_name": "Zacian",
        "mascot_num": 888,
        "header_bg": "bg-cyan-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-cyan-500 text-white",
        "border_color": "border-cyan-600",
        "progress_color": "bg-cyan-600",
    },
    {
        "slug": "shield",
        "name": "Pokémon Escudo",
        "generation": 8,
        "platform": "Nintendo Switch",
        "mascot_name": "Zamazenta",
        "mascot_num": 889,
        "header_bg": "bg-rose-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-rose-500 text-white",
        "border_color": "border-rose-600",
        "progress_color": "bg-rose-600",
    },
    {
        "slug": "brilliant-diamond",
        "name": "Pokémon Diamante Brillante",
        "generation": 8,
        "platform": "Nintendo Switch",
        "mascot_name": "Dialga",
        "mascot_num": 483,
        "header_bg": "bg-sky-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-sky-500 text-white",
        "border_color": "border-sky-600",
        "progress_color": "bg-sky-600",
    },
    {
        "slug": "shining-pearl",
        "name": "Pokémon Perla Reluciente",
        "generation": 8,
        "platform": "Nintendo Switch",
        "mascot_name": "Palkia",
        "mascot_num": 484,
        "header_bg": "bg-fuchsia-600",
        "header_text": "text-white font-black",
        "badge_bg": "bg-fuchsia-500 text-white",
        "border_color": "border-fuchsia-600",
        "progress_color": "bg-fuchsia-600",
    },
    {
        "slug": "legends-arceus",
        "name": "Leyendas Pokémon: Arceus",
        "generation": 8,
        "platform": "Nintendo Switch",
        "mascot_name": "Arceus",
        "mascot_num": 493,
        "header_bg": "bg-teal-700",
        "header_text": "text-teal-100 font-black",
        "badge_bg": "bg-teal-800 text-white",
        "border_color": "border-teal-700",
        "progress_color": "bg-teal-700",
    },

    # --- Generación 9 (Nintendo Switch) ---
    {
        "slug": "scarlet",
        "name": "Pokémon Escarlata",
        "generation": 9,
        "platform": "Nintendo Switch",
        "mascot_name": "Koraidon",
        "mascot_num": 1007,
        "header_bg": "bg-red-700",
        "header_text": "text-white font-black",
        "badge_bg": "bg-red-600 text-white",
        "border_color": "border-red-700",
        "progress_color": "bg-red-700",
    },
    {
        "slug": "violet",
        "name": "Pokémon Púrpura",
        "generation": 9,
        "platform": "Nintendo Switch",
        "mascot_name": "Miraidon",
        "mascot_num": 1008,
        "header_bg": "bg-purple-700",
        "header_text": "text-white font-black",
        "badge_bg": "bg-purple-600 text-white",
        "border_color": "border-purple-700",
        "progress_color": "bg-purple-700",
    },
    {
        "slug": "legends-za",
        "name": "Leyendas Pokémon: Z-A",
        "generation": 9,
        "platform": "Nintendo Switch",
        "mascot_name": "Zygarde",
        "mascot_num": 718,
        "header_bg": "bg-emerald-700",
        "header_text": "text-emerald-100 font-black",
        "badge_bg": "bg-emerald-800 text-white",
        "border_color": "border-emerald-700",
        "progress_color": "bg-emerald-700",
    },
]
