# Generated by Django 6.1.1 on 2026-09-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('generation', models.PositiveSmallIntegerField(default=1)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['generation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField(max_length=500)),
                ('sprite_shiny_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_type', models.CharField(max_length=30)),
                ('secondary_type', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Altura en decímetros', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Peso en hectogramos', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['national_number'],
            },
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('is_national', models.BooleanField(default=False)),
                ('pokeapi_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedexes', to='tracker.game')),
            ],
            options={
                'verbose_name': 'Pokédex',
                'verbose_name_plural': 'Pokédexes',
                'ordering': ['game', 'id'],
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.PositiveIntegerField()),
                ('pokedex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.pokedex')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_appearances', to='tracker.pokemon')),
            ],
            options={
                'verbose_name': 'Entrada de Pokédex',
                'verbose_name_plural': 'Entradas de Pokédex',
                'ordering': ['entry_number'],
            },
        ),
        migrations.CreateModel(
            name='UserPokemonCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_caught', models.BooleanField(default=False)),
                ('is_shiny', models.BooleanField(default=False)),
                ('caught_at', models.DateTimeField(blank=True, null=True)),
                ('pokedex_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_catches', to='tracker.pokedexentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captura de Usuario',
                'verbose_name_plural': 'Capturas de Usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='pokedexentry',
            index=models.Index(fields=['pokedex', 'entry_number'], name='tracker_pok_pokedex_41010d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pokedexentry',
            unique_together={('pokedex', 'entry_number')},
        ),
        migrations.AddIndex(
            model_name='userpokemoncatch',
            index=models.Index(fields=['user', 'pokedex_entry'], name='tracker_use_user_id_6e7525_idx'),
        ),
        migrations.AddIndex(
            model_name='userpokemoncatch',
            index=models.Index(fields=['session_key', 'pokedex_entry'], name='tracker_use_session_b38c23_idx'),
        ),
    ]
