# Generated by Django 6.1.1 on 2026-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='game_sprite_url',
            field=models.URLField(blank=True, help_text='Sprite específico de la generación/juego', max_length=500, null=True),
        ),
    ]
