# Generated by Django 6.1.1 on 2026-09-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_pokedexentry_game_sprite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='primary_type',
            field=models.CharField(blank=True, help_text='Tipo primario en la generación de este juego', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pokedexentry',
            name='secondary_type',
            field=models.CharField(blank=True, help_text='Tipo secundario en la generación de este juego', max_length=30, null=True),
        ),
    ]
