# Generated by Django 6.1.1 on 2026-09-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_pokedexentry_primary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='flavor_text',
            field=models.TextField(blank=True, help_text='Descripción de la Pokédex específica de este juego'),
        ),
        migrations.AddField(
            model_name='pokedexentry',
            name='obtaining_info',
            field=models.JSONField(blank=True, default=dict, help_text='Información detallada de cómo obtenerlo en este juego'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='category',
            field=models.CharField(blank=True, help_text='Categoría o especie en español (ej: Pokémon Semilla)', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos crudos de pokemon-species de PokeAPI'),
        ),
    ]
