# Generated by Django 6.1.1 on 2026-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_pokedexentry_flavor_text_pokedexentry_obtaining_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='is_custom_override',
            field=models.BooleanField(default=False, help_text='Si está activo, las sincronizaciones automáticas no sobreescribirán esta entrada'),
        ),
    ]
