# Generated by Django 6.1.1 on 2026-09-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_pokedexentry_is_custom_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Nombre oficial en español', max_length=100)),
                ('generation', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=30)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('pp', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_class', models.CharField(blank=True, max_length=30)),
                ('effect_description', models.TextField(blank=True, help_text='Descripción del efecto en español')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pokedexentry',
            name='game_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos completos y enriquecidos de este juego (stats Gen 1, movimientos, ratio de captura, etc.)'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='encounters_data',
            field=models.JSONField(blank=True, default=list, help_text='Datos crudos de encuentros de PokeAPI'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution_chain_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos crudos de la cadena evolutiva de PokeAPI'),
        ),
    ]
