# Generated by Django 6.1.1 on 2026-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_move_pokedexentry_game_data_pokemon_encounters_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='sprite_shiny_url',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='encounters_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_chain_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='species_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
