# Generated by Django 6.1.1 on 2026-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_pokemon_sprite_shiny_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpokemoncatch',
            name='unown_forms_caught',
            field=models.JSONField(blank=True, default=dict, help_text="Formas capturadas de Unown: {'normal': [...], 'shiny': [...]}"),
        ),
    ]
