# Generated by Django 6.1.1 on 2026-09-24 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_userpokemoncatch_unown_forms_caught'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.AlterUniqueTogether(
            name='pokedexentry',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='pokedexentry',
            name='tracker_pok_pokedex_41010d_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpokemoncatch',
            name='tracker_use_user_id_6e7525_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpokemoncatch',
            name='tracker_use_session_b38c23_idx',
        ),
        migrations.AddField(
            model_name='userpokemoncatch',
            name='entry_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userpokemoncatch',
            name='entry_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userpokemoncatch',
            name='game_slug',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='userpokemoncatch',
            index=models.Index(fields=['user', 'game_slug'], name='tracker_use_user_id_452e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpokemoncatch',
            index=models.Index(fields=['session_key', 'game_slug'], name='tracker_use_session_f0e688_idx'),
        ),
        migrations.AddIndex(
            model_name='userpokemoncatch',
            index=models.Index(fields=['game_slug', 'entry_id'], name='tracker_use_game_sl_67e959_idx'),
        ),
        migrations.AddIndex(
            model_name='userpokemoncatch',
            index=models.Index(fields=['game_slug', 'entry_number'], name='tracker_use_game_sl_73d663_idx'),
        ),
        migrations.RemoveField(
            model_name='pokedexentry',
            name='pokedex',
        ),
        migrations.RemoveField(
            model_name='pokedexentry',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='userpokemoncatch',
            name='pokedex_entry',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='PokedexEntry',
        ),
    ]
