# Generated by Django 6.1.1 on 2026-09-29 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_delete_move_alter_pokedexentry_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpokemoncatch',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'game_slug', 'entry_number'), name='unique_user_game_entry'),
        ),
        migrations.AddConstraint(
            model_name='userpokemoncatch',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'game_slug', 'entry_number'), name='unique_session_game_entry'),
        ),
    ]
